cvt.officebau.com/Controllers/TDS_HRAController.cs
using cvt.officebau.com.Utilities;
using cvt.officebau.com.Services;
using cvt.officebau.com.ViewModels;
using System;
using System.Collections.Generic;
using System.Data;
using System.Web.Mvc;

namespace cvt.officebau.com.Controllers
{
    [SessionExpire]
    public class TDS_HRAController : Controller
    {
        #region TDS_HRADeclaration
        UtilityRepository utilityRepository = new UtilityRepository();

        public ActionResult TDS_HRADeclaration()
        {
            Utility.SetSession("MenuRetention", "TDS");
            Utility.SetSession("SubMenuRetention", "HRADECLARATION");
             UtilityRepository track= new UtilityRepository(); track.TrackFormNavigation("HRA DECLARATION");

            MasterDataRepository masterDataRepository = new MasterDataRepository();
            TdsHrabo tdsDeclaration = new TdsHrabo
            {
                FinancialYearList = masterDataRepository.SearchMasterDataDropDown("FinancialYear", string.Empty)
            };
            tdsDeclaration.FinancialYearList = utilityRepository.GetFinancialYearText();
            return View(tdsDeclaration);
        }

        #endregion TDS_HRADeclaration

        #region SaveTDS_HRA

        [HttpPost]
        public ActionResult SaveTDS_HRA(IList<TdsHrabo> tdsHraboList)
        {
            string result = string.Empty;
            RbsRepository rbsRepository = new RbsRepository();
            bool hasAccess = rbsRepository.IsAuthorized(Utility.UserId(), tdsHraboList[0].MenuCode, tdsHraboList[0].Id == 0 ? "Save" : "Edit");
            if (!hasAccess)
            {
                return Json(Constants.UnAuthorizedAccess, JsonRequestBehavior.AllowGet);
            }

            foreach (TdsHrabo list in tdsHraboList)
            {
                result = _tdsHraRepository.ManageHraDeclare(list);
            }

            return Json(result);
        }

        #endregion SaveTDS_HRA

        #region TDS_HRAClarance

        public ActionResult TDS_HRAClarance()
        {
            Utility.SetSession("MenuRetention", "TDS");
            Utility.SetSession("SubMenuRetention", "HRACLEARANCE");
             UtilityRepository track= new UtilityRepository(); track.TrackFormNavigation("HRA Clearance");

            MasterDataRepository masterDataRepository = new MasterDataRepository();
            TdsHrabo tdsDeclaration = new TdsHrabo
            {
                FinancialYearList = masterDataRepository.SearchMasterDataDropDown("FinancialYear", string.Empty)
            };
            tdsDeclaration.FinancialYearList = utilityRepository.GetFinancialYearText();
            return View(tdsDeclaration);
        }

        #endregion TDS_HRAClarance

        #region EmployeeList

        public ActionResult EmployeeList(TdsHrabo tdsHrabo)
        {
            return PartialView(_tdsHraRepository.SearchEmployee(tdsHrabo));
        }

        #endregion EmployeeList

        #region HRAClearanceList

        public ActionResult HraClearanceList(int? financialYearId, int? employeeId)
        {
            TdsHrabo tdsDeclaration = new TdsHrabo
            {
                EmployeeId = Convert.ToInt32(employeeId),
                FinancialYearId = Convert.ToInt32(financialYearId)
            };
            return PartialView(_tdsHraRepository.SearchTdsClearance(tdsDeclaration));
        }

        #endregion HRAClearanceList

        #region HRADeclarationList

        public ActionResult HraDeclarationList(int? financialYearId, int employeeId)
        {
            TdsHrabo tdsDeclaration = new TdsHrabo
            {
                EmployeeId = employeeId == 0 ? Utility.UserId() : employeeId,
                FinancialYearId = financialYearId
            };

            return PartialView(_tdsHraRepository.Search_TDSHRADeclaration(tdsDeclaration));
        }

        #endregion HRADeclarationList

        #region Search HRA Declaration

        public ActionResult SearchHraDeclaration()
        {
            Utility.SetSession("MenuRetention", "TDS");
            Utility.SetSession("SubMenuRetention", "HRADECLARATION-HR");
             UtilityRepository track= new UtilityRepository(); track.TrackFormNavigation("HRA DECLARATION - HR");

            MasterDataRepository masterDataRepository = new MasterDataRepository();
            TdsHrabo tdsDeclaration = new TdsHrabo
            {
                FinancialYearList = masterDataRepository.SearchMasterDataDropDown("FinancialYear", string.Empty)
            };
            tdsDeclaration.FinancialYearList = utilityRepository.GetFinancialYearText();
            return View(tdsDeclaration);
        }

        #endregion Search HRA Declaration

        #region Variables

        private readonly TdsHraRepository _tdsHraRepository = new TdsHraRepository();

        #endregion Variables

        #region TDS IT Declaration Report

        public ActionResult TDS_SearchITDeclarationRPT()
        {
            MasterDataRepository masterDataRepository = new MasterDataRepository();

            TdsHrabo tdsDeclaration = new TdsHrabo
            {
                FinancialYearList = masterDataRepository.SearchMasterDataDropDown("Financialyear", string.Empty)
            };
            tdsDeclaration.FinancialYearList = utilityRepository.GetFinancialYearText();
            return PartialView(tdsDeclaration);
        }

        public ActionResult TDS_ITDeclarationRPTList(int financialyearId, string formType)
        {
            DataTable dataTable = _tdsHraRepository.TDSITDeclarationRPTList(financialyearId, formType);
            return PartialView(dataTable);
        }

        #endregion TDS IT Declaration Report

        #region TSD HRA Clearance Report

        public ActionResult TDS_SearchHRAClearanceRPT()
        {
            MasterDataRepository masterDataRepository = new MasterDataRepository();

            TdsHrabo tdsDeclaration = new TdsHrabo
            {
                FinancialYearList = masterDataRepository.SearchMasterDataDropDown("Financialyear", string.Empty)
            };
            tdsDeclaration.FinancialYearList = utilityRepository.GetFinancialYearText();
            return PartialView(tdsDeclaration);
        }

        public ActionResult TDS_HRAClearanceRPTList(int financialyearId, string status)
        {
            DataTable dataTable = _tdsHraRepository.TDSHRAClearanceRPTList(financialyearId, status);
            return PartialView(dataTable);
        }

        #endregion TDS HRA Clearance Report
    }
}

cvt.officebau.com/Views/TDS_HRA/EmployeeList.cshtml
@model IEnumerable<TdsHrabo>
<div class="box box-info">
    <div class="box-header with-border clickable1 handicon margin-bottom">
        <div class="box-title">
            <span class="pull-left ">
                <i class="glyphicon  glyphicon-triangle-bottom"></i>
            </span> &nbsp;&nbsp; Employee List
        </div>
    </div>
    <div id="resize_wrapper" class="box-body">
        @if (!Model.Any())
        {
            <div class="text-center panel-body">
                No data available.
            </div>
            <script>
                $(document).ready(function () {
                    $("#searchlist").prop('disabled', true);
                })
            </script>
        }
        else
        {
            <table class="table dt-responsive table-striped table-bordered nowrap" id="employeeTDSCLR_Grid">
                <thead>
                    <tr>
                        <th id="th1">Employee Name</th>
                        <th id="th2">Code</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                {
                        <tr class="handicon" id="@item.EmployeeId" onclick="getEmployeeClearance(@item.EmployeeId, this)">
                            @Html.HiddenFor(model => item.EmployeeId)
                            <td>
                                @Html.DisplayFor(model => item.EmployeeName)
                            </td>
                            <td>@Html.DisplayFor(model => item.EmployeeCode)</td>
                        </tr>
                    }
                </tbody>
            </table>
        }
    </div>
</div>
<script>

    $(document).ready(function () {
        $('#employeeTDSCLR_Grid tbody tr').first().click();
    });
    $('#employeeTDSCLR_Grid').DataTable({
        "bFilter": true,
        "bPaginate": true,
        "aaSorting": [],
        responsive: true,
        pageResize: false,
        "sPaginationType": "simple",

    });
    $("#employeeTDSCLR_Grid_info").hide();
    $('.col-sm-5').removeClass('col-sm-5');

    $('.col-sm-7').addClass('col-sm-12');
    $('.col-sm-7').removeClass('col-sm-7');

    $('.col-sm-6').removeClass('col-sm-6');
    $("#employeeTDSCLR_Grid_filter").removeClass('dataTables_filter').addClass("text-center");
    $('#employeeTDSCLR_Grid_length').css('display', 'none');

    function getEmployeeClearance(employeeId, cur) {
        $("#employeeTDSHRA").removeAttr('style');
        _HraEmpID = employeeId;
        $('#employeeTDSCLR_Grid tbody tr[style]').removeClass('selected');
        $('#employeeTDSCLR_Grid tbody tr[style]').removeAttr('style');
        $(cur).css({ "background-color": "#0D92F2 !important", "color": "Black" });
        $(cur).addClass('selected');
        if ($("#financialyearid option:selected").text() != '-- Select --') {
            getAjaxCall('@(Url.Action("HRAClearanceList", "TDS_HRA"))', 
                { financialYearId: $("#financialyearid").val(), employeeId: employeeId },
                'employeeTDSHRA');
        } else {
            $("#employeeTDSHRA").empty().html('Please select the Financial Year.').css('padding', '60px');
            $("#employeeTDSHRA").css('text-align', 'center');
        }
    }
</script>

cvt.officebau.com/Views/TDS_HRA/HraClearanceList.cshtml
@model IList<TdsHrabo>

@if (!Model.Any())
{
    <div class="text-center panel-body">
        No data available.
    </div>
}
else
{
    <div id="resize_wrapper">
        @using (Html.BeginForm("SaveTDS_HRA", "TDS_HRA", FormMethod.Post, new { id = "SaveHRAClearanceList" }))
        {
            <table class="table dt-responsive table-striped table-bordered nowrap" id="TDS_clr">
                <thead>
                    <tr>
                        <th class="text-center">Month</th>
                        <th class="text-center">Submitted</th>
                        <th class="text-center">Cleared</th>
                        <th class="text-center">Remarks</th>
                    </tr>
                </thead>
                <tbody>
                    @for (var i = 0; i < Model.Count; i++)
                    {
                        <tr id="@Model[i].Id">
                            @Html.HiddenFor(m => Model[0].MenuCode, new { id = "HRAClearanceMenuCode" })
                            <td class="text-center">
                                @Html.DisplayFor(modelItem => Model[i].Month.Name)
                                @Html.HiddenFor(modelItem => Model[i].Id)
                                @Html.HiddenFor(modelItem => Model[i].Month.Name, new { id = "monthyearid" + Model[i].Id })
                                @Html.HiddenFor(modelItem => Model[i].Month.Id, new { id = "monthid" + Model[i].Id })
                                @Html.HiddenFor(modelItem => Model[i].Year.Id, new { id = "yearid" + Model[i].Id })
                                @Html.HiddenFor(modelItem => Model[i].EmployeeId, new { id = "empid" + Model[i].Id })
                                @Html.HiddenFor(modelItem => Model[i].StartYear.Id, new { id = "startyearid" + Model[i].Id })
                                @Html.HiddenFor(modelItem => Model[i].Declaration, new { id = "HRAdeclaration" + Model[i].Id })
                                @Html.HiddenFor(modelItem => Model[i].FinancialYearId, new { id = "financialyearID" })
                            </td>
                            <td class="text-right">
                                @Html.DisplayFor(modelItem => Model[i].Submitted, string.Format("{0:0.00}", Model[i].Submitted))
                                @Html.HiddenFor(modelItem => Model[i].Submitted, new { id = "HRAsubmitted" + Model[i].Id })
                            </td>
                            <td class="text-right">
                                @if (Model[i].IsProofOpen && Model[i].IsFinancialYear)
                                {
                                    if (Model[i].Id != 0)
                                    {
                                        @Html.TextBoxFor(modelItem => Model[i].Cleared, string.Format("{0:0.00}", Model[i].Cleared), new { @class = "text-right input-xs", id = "HRAclearance" + Model[i].Id, type = "number", onkeyup = "HRAclearanceamountnotminus(" + Model[i].Id + ")" })
                                    }
                                    else
                                    {
                                        @Html.DisplayFor(modelItem => Model[i].Cleared)
                                        @Html.HiddenFor(modelItem => Model[i].Submitted)
                                    }
                                }
                                else
                                {
                                    @Html.DisplayFor(modelItem => Model[i].Cleared)
                                    @Html.HiddenFor(modelItem => Model[i].Submitted)
                                }
                            </td>
                            <td>
                                @if (Model[i].IsOpen && Model[i].IsFinancialYear)
                                {
                                    @Html.TextBoxFor(modelItem => Model[i].Remarks, new { @class = "input-xs", id = "HRAremarks" + Model[i].Id, maxlength = "8000" })
                                }
                                else if (Model[i].IsProofOpen && Model[i].IsFinancialYear)
                                {
                                    if (Model[i].Id != 0)
                                    {
                                        @Html.TextBoxFor(modelItem => Model[i].Remarks, new { @class = "input-xs", id = "HRAremarks" + Model[i].Id , maxlength = "8000" })
                                    }
                                    else
                                    {
                                        @Html.DisplayFor(modelItem => Model[i].Remarks)
                                    }
                                }
                                else
                                {
                                    @Html.DisplayFor(modelItem => Model[i].Remarks)
                                }
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        }
    </div>
    <footer class="main-footer navbar-fixed-bottom">
        <div class="row">
            <div class="col-md-6 hidemodified">
            </div>
            <div class="col-md-offset-3 col-md-3 col-xs-12 text-right">
                @if (Model.Any())
                {
                    if (Model.Count(a => a.IsOpen) != 0 && Model.Count(a => a.IsFinancialYear) != 0)
                    {
                        <button class="btn btn-primary btn-md" type="button" title="Please click to Save" onclick="SaveClearance()">
                            <span class="glyphicon glyphicon-floppy-save"></span> Update
                        </button>
                    }
                    else if (Model.Count(a => a.IsProofOpen) != 0 && Model.Count(a => a.IsFinancialYear) != 0)
                    {
                        <button class="btn btn-md btn-primary" title="Please click to Update" type="button" onclick="SaveClearance()"><i class="glyphicon glyphicon-floppy-save"></i> Update</button>
                    }
                    else
                    {
                        <button class="btn btn-primary btn-md" type="button" title="Please click to Save" disabled>
                            <span class="glyphicon glyphicon-floppy-save"></span> Update
                        </button>
                    }
                }
            </div>
        </div>
    </footer>
}
<script>
    function HRAclearanceamountnotminus(id) {
        $("#HRAclearance" + id).val($("#HRAclearance" + id).val().replace(/[ -]/g, ''));
    }

    $(document).ready(function () {
        $(".input-xs").each(function () {
            if ($(this).val() == 0.00) {
                $(this).val("");
            }
        });
        $("#HRAClearanceMenuCode").val('HRACLR');
    });
    $(document).ready(function () {
        $('#TDS_clr').dataTable({
            "bFilter": false,
            "bPaginate": false,
            "pagingType": "simple",
            "aaSorting": [],
            "bInfo": false,
            responsive: true,
            bautoheight: true
        });
    });

    function SaveClearance() {
        $.post($('#SaveHRAClearanceList').attr("action"),
            $('#SaveHRAClearanceList').serialize(),
            function (r) {
                if (r.indexOf("Successfully") !== -1) {
                    $.notify({
                        message: r
                    },
                        {
                            type: 'success',
                            timer: 4000
                        });
                } else {
                    $.notify({
                        message: r
                    },
                        {
                            type: 'warning',
                            timer: 4000
                        });
                }
            });
        setTimeout(function () { 
            getAjaxCall('@(Url.Action("EmployeeList", "TDS_HRA"))', {}, 'employeelist');
        },
            400);
    }

    function moreDespText(id) {
        var description = $("#HRAremarks" + id).val();
        $("#descriptionPurMore").val(description);
    }
</script>

cvt.officebau.com/Views/TDS_HRA/HraDeclarationList.cshtml
@model IList<TdsHrabo>
<style>
    @@media only screen and (max-width: 760px), (min-device-width: 768px) and (max-device-width: 1024px) {
        #resize_wrapper {
            overflow: auto;
        }
    }
</style>
<div id="resize_wrapper">
    @using (Html.BeginForm("SaveTDS_HRA", "TDS_HRA", FormMethod.Post, new { id = "SaveTDSHRAList" }))
    {

        <table class="table dt-responsive table-striped table-bordered nowrap" id="TDS_hra">
            <thead>
                <tr>
                    <th class="text-center">Month</th>
                    <th class="text-center">Declaration</th>
                    <th class="text-center">Submitted</th>
                    <th class="text-center">Cleared</th>
                    <th class="text-center">Remarks</th>
                </tr>
            </thead>
            <tbody>

                @for (var i = 0; i < Model.Count; i++)
                {
                    <tr id="@Model[i].Id">
                        @Html.HiddenFor(m => Model[0].MenuCode, new { id = "HRADeclarationMenuCode" })
                        <td>
                            @Html.DisplayFor(modelItem => Model[i].Month.Name)
                            @Html.HiddenFor(m => Model[i].Id)
                            @Html.HiddenFor(modelItem => Model[i].Month.Name, new { id = "monthyearid" + Model[i].Id })
                            @Html.HiddenFor(modelItem => Model[i].Month.Id, new { id = "monthid" + Model[i].Id })
                            @Html.HiddenFor(modelItem => Model[i].Year.Id, new { id = "yearid" + Model[i].Id })
                            @Html.HiddenFor(modelItem => Model[i].StartYear.Id, new { id = "startyearid" + Model[i].Id })
                            @Html.HiddenFor(modelItem => Model[i].EmployeeId, new { id = "empid" + Model[i].Id })
                            @Html.HiddenFor(modelItem => Model[i].FinancialYearId, new { id = "f" + Model[i].Id })
                        </td>
                        <td class="text-right">
                            @if (Model[i].IsOpen && Model[i].IsFinancialYear)
                            {
                                @Html.TextBoxFor(modelItem => Model[i].Declaration, string.Format("{0:0.00}", Model[i].Declaration), new { @class = "text-right input-xs", id = "HRAdeclaration" + Model[i].Id, type = "number", onkeyup = "HRAdeclarationamountnotminus(" + Model[i].Id + ")" })
                            }
                            else
                            {
                                @Html.DisplayFor(modelItem => Model[i].Declaration)
                                @Html.HiddenFor(modelItem => Model[i].Declaration)
                            }
                        </td>
                        <td class="text-right">
                            @if (Model[i].IsProofOpen && Model[i].IsFinancialYear)
                            {
                                @Html.TextBoxFor(modelItem => Model[i].Submitted, string.Format("{0:0.00}", Model[i].Submitted), new { @class = "text-right input-xs", id = "HRAsubmitted" + Model[i].Id, type = "number", onkeyup = "HRAsubmittedamountnotminus(" + Model[i].Id + ")" })
                            }
                            else
                            {
                                @Html.DisplayFor(modelItem => Model[i].Submitted)
                                @Html.HiddenFor(modelItem => Model[i].Submitted)
                            }
                        </td>
                        <td class="text-right">
                            @Html.DisplayFor(modelItem => Model[i].Cleared)
                            @Html.HiddenFor(modelItem => Model[i].Cleared, new { id = "HRAclearance" + Model[i].Id })
                        </td>
                        <td title="@Model[i].Remarks">
                            @Html.HiddenFor(modelItem => Model[i].Remarks, new { id = "HRAremarks" + Model[i].Id })
                            @if (Model[i].Remarks.Length > 15)
                            {
                                @Html.DisplayFor(model => Model[i].Remarks).ToString().Substring(0, 15)
                            }
                            else
                            {
                                @Html.DisplayFor(model => Model[i].Remarks)
                                @Html.HiddenFor(model => Model[i].Remarks)
                            }
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
</div>
    <footer class="main-footer navbar-fixed-bottom">
        <div class="row">
            <div class="col-md-6 hidemodified">
            </div>
            <div class="col-md-offset-3 col-md-3 col-xs-12 text-right">
                @if (Model.Any())
                {
                    if (Model.Count(a => a.IsOpen) != 0 && Model.Count(a => a.IsFinancialYear) != 0)
                    {
                        <button class="btn btn-primary btn-md" type="button" title="Update" onclick="SaveDeclaration()">
                            <span class="glyphicon glyphicon-floppy-save"></span> Update
                        </button>
                    }
                    else if (Model.Count(a => a.IsProofOpen) != 0 && Model.Count(a => a.IsFinancialYear) != 0)
                    {
                        <button class="btn btn-md btn-primary" title="Update" type="button" onclick="SaveDeclaration()"><i class="glyphicon glyphicon-floppy-save"></i> Update</button>
                    }
                    else
                    {
                        <button class="btn btn-primary btn-md" type="button" title="Update" disabled>
                            <span class="glyphicon glyphicon-floppy-save"></span> Update
                        </button>
                    }
                }
            </div>
        </div>
    </footer>

<script>
    function HRAdeclarationamountnotminus(id) {
        $("#HRAdeclaration" + id).val($("#HRAdeclaration" + id).val().replace(/[ -]/g, ''));
    }

    function HRAsubmittedamountnotminus(id) {
        $("#HRAsubmitted" + id).val($("#HRAsubmitted" + id).val().replace(/[ -]/g, ''));
    }

    $(document).ready(function () {
        $(".input-xs").each(function () {
            if ($(this).val() === 0.00 || $(this).val() === "0.00") {
                $(this).val("");
            }
        });
        if (_EMPTDSID != 0 && _EMPTDSID != "" && _EMPTDSID != null) {
            $("#HRADeclarationMenuCode").val('HRADECHR');
        } else {
            $("#HRADeclarationMenuCode").val('HRADEC');
        }
    });

    $(document).ready(function () {
        $('#TDS_hra').dataTable({
            "bFilter": false,
            "bPaginate": false,
            "aaSorting": [],
            "bInfo": false,
            responsive: true,
            bautoheight: true
        });
    });

    function SaveDeclaration() {
        $.post($('#SaveTDSHRAList').attr("action"),
            $('#SaveTDSHRAList').serialize(),
            function (r) {
                if (r.indexOf("Successfully") !== -1) {
                    $.notify({
                        message: r
                    },
                        {
                            type: 'success',
                            timer: 4000
                        });
                } else {
                    $.notify({
                        message: r
                    },
                        {
                            type: 'warning',
                            timer: 4000
                        });
                }
                if (_EMPTDSID !== 0) {
                    setTimeout(function () {
                        searchHRADeclaration();
                    },
                        400);
                } else {
                    setTimeout(function () { 
                        location.href = '@(Url.Action("TDS_HRADeclaration", "TDS_HRA"))?menuCode=HRADEC';
                    },
                        400);
                }
            });
    }
</script>

cvt.officebau.com/Views/TDS_HRA/TDS_HRAClarance.cshtml
@model TdsHrabo
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<html>
<head>
    <title>
        OfficeBAU - HRA Clearance
    </title>
</head>
<body>
    <section class="content-header">
        <h1>
            <span id="spnHeaderName"></span>
        </h1>
    </section>
    <div class="content">
        <div class="row">
            <div class="col-md-3">
                <div id="employeelist"></div>
            </div>
            <div class="col-md-9 col-xs-12">
                <div class="box box-info">
                    <div class="box-body">
                        <div class="box-title">
                            <div class="col-md-3">
                                HRA Clearance
                            </div>
                            <div class="col-md-1 text-right">
                                <span>FY</span>
                            </div>
                            <div class="col-md-3">
                                @Html.DropDownListFor(model => model.FinancialYearId, Model.FinancialYearList, new { @class = "form-control", id = "financialyearid" })
                                @Html.HiddenFor(model => model.EmployeeId, new { id = "EmpID" })
                            </div>
                        </div>
                    </div>
                    <div class="panel-body">
                        <div id="employeeTDSHRA">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="MorePurDescription" data-backdrop="static" data-keyboard="false">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="false">×</button>
                    <h4 class="modal-title">Remarks</h4>
                </div>
                <div class="modal-body">
                    <textarea id="descriptionPurMore" class="form-controls TextArea-more"></textarea>
                </div>
                <div class="modal-footer">
                    <a href="#" onclick="savePurDesp()" class="btn btn-danger">Save</a>
                </div>
            </div>
        </div>
    </div>
    <script>
        $(document).on('click',
            '.clickable1',
            function (e) {
                var $this = $(this);
                if (!$this.hasClass('panel-collapsed')) {
                    $this.parents('.box').find('.box-body').slideUp();
                    $this.addClass('panel-collapsed');
                    $this.find('i').removeClass('glyphicon-triangle-bottom').addClass('glyphicon-triangle-right');
                } else {
                    $this.parents('.box').find('.box-body').slideDown();
                    $this.removeClass('panel-collapsed');
                    $this.find('i').removeClass('glyphicon-triangle-right').addClass('glyphicon-triangle-bottom');
                }
            });
        $(document).ready(function () {  
            getAjaxCall('@(Url.Action("EmployeeList", "TDS_HRA"))', {}, 'employeelist');
        });
        var currentDate = new Date(),
            year = currentDate.getFullYear(),
            finyear = year - 1,
            month = currentDate.getMonth() + 1;
        if (month < 4)
            year = finyear + " -";
        else
            year = year + " -";
        $("#financialyearid option:contains(" + year + ")").attr('selected', true);
        var financialYearID = $("#financialyearid option:selected").val();

        function savePurDesp() {
            var description = $("#descriptionPurMore").val();
            $("#itemRemarks").val(description);
            $("#MorePurDescription").modal('hide');
        }

        function ClosePurDesp() {
            $("#MorePurDescription").modal('hide');
        }

        $("#MorePurDescription").draggable();
        $("#financialyearid").change(function () {
            financialYearID = $("#financialyearid option:selected").val();
            if ($("#financialyearid option:selected").text() !== '-- Select --') {
                $("#employeeTDSHRA").removeAttr('style');
                getAjaxCall('@(Url.Action("HRAClearanceList", "TDS_HRA"))',
                    { financialYearId: financialYearID, employeeId: _HraEmpID },
                    'employeeTDSHRA');
            } else {
                $("#employeeTDSHRA").empty().html('Please select the Financial Year.').css('padding', '60px');
                $("#employeeTDSHRA").css('text-align', 'center');
            }
        });
    </script>
</body>
</html>