cvt.officebau.com/Controllers/PurchaseOrderController.cs
using cvt.officebau.com.Utilities;
using cvt.officebau.com.Services;
using cvt.officebau.com.ViewModels;
using System.Collections.Generic;
using System.Web.Mvc;

namespace cvt.officebau.com.Controllers
{
    [SessionExpire]
    public class PurchaseOrderController : Controller
    {
        // GET: PurchaseOrder

        public ActionResult Index(string menuCode, int? id, string screenType)
        {
            if (!string.IsNullOrWhiteSpace(menuCode))
            {
                Utility.SetSession("MenuID", menuCode);
            }

            Utility.SetSession("MenuRetention", "PURCHASE");
            Utility.SetSession("SubMenuRetention", "PURCHASEORDER");
             UtilityRepository track= new UtilityRepository(); track.TrackFormNavigation("PURCHASEORDER");
            SearchParamsBo searchParamsBo = new SearchParamsBo
            {
                Id = id ?? 0,
                ScreenType = screenType
            };
            return View(searchParamsBo);
        }

        public ActionResult PurchaseOrderDetails(SearchParamsBo searchParamsBo)
        {
            return PartialView(_purchaseOrderRepository.SearchPurchaseOrder(searchParamsBo));
        }

        public ActionResult CreateNewPurchaseOrder(int id, string menuCode)
        {
            if (!string.IsNullOrWhiteSpace(menuCode))
            {
                Utility.SetSession("MenuID", menuCode);
            }

            ExpenseItemsBO expenseItemBo = new ExpenseItemsBO();
            ExpenseDetailsBO expenseDetailsBo = new ExpenseDetailsBO();
            ExpenseBo expenseBo = _purchaseOrderRepository.GetPoDetails(id);
            MasterDataRepository masterDataRepository = new MasterDataRepository();
            ApplicationConfigurationRepository applicationConfigurationRepository = new ApplicationConfigurationRepository();
            if (id == 0)
            {
                expenseBo.ExpenseDetail = new List<ExpenseDetailsBO>();
                expenseBo.ExpenseItems = new List<ExpenseItemsBO>();
                expenseBo.ExpenseDetail.Add(expenseDetailsBo);
                expenseBo.ExpenseItems.Add(expenseItemBo);
                expenseDetailsBo.LedgerList = masterDataRepository.GetPreRequestProductLedger("Ledger");
                expenseItemBo.ProductList = masterDataRepository.GetPreRequestProduct("Purchase");
            }

            expenseDetailsBo.LedgerList = masterDataRepository.GetPreRequestProductLedger("Ledger");
            expenseBo.CostCenterList = masterDataRepository.SearchMasterDataDropDown("CostCenter");
            expenseItemBo.ProductList = masterDataRepository.GetPreRequestProduct("Purchase");
            expenseBo.IsCostCenter = applicationConfigurationRepository.SearchCostCenter();
            expenseBo.MenuCode = menuCode;
            return PartialView(expenseBo);
        }

        [HttpPost]
        public ActionResult CreateNewPurchaseOrder(ExpenseBo expenseBo)
        {
            RbsRepository rbsRepository = new RbsRepository();
            bool hasAccess = false;
            if (expenseBo != null)
            {
                hasAccess = rbsRepository.IsAuthorized(Utility.UserId(), expenseBo.MenuCode, expenseBo.Id == 0 ? "Save" : "Edit");
            }

            if (expenseBo != null && expenseBo.IsDeleted)
            {
                hasAccess = rbsRepository.IsAuthorized(Utility.UserId(), expenseBo.MenuCode, "Delete");
            }

            if (!hasAccess)
            {
                return Json(Constants.UnAuthorizedAccess);
            }

            return Json(_purchaseOrderRepository.ManagePo(expenseBo), JsonRequestBehavior.AllowGet);
        }

        #region Variables


        private readonly PurchaseOrderRepository _purchaseOrderRepository = new PurchaseOrderRepository();

        #endregion Variables
    }
}

cvt.officebau.com/Views/PurchaseOrder/PurchaseOrderDetails.cshtml
@model IList<ExpenseBo>
<div class="box box-primary">
    <div class="box-body">
        @{
            var Check = string.Empty;
        }
        <style>
            @@media only screen and (max-width: 760px), (min-device-width: 768px) and (max-device-width: 1024px) {
                /* Force table to not be like tables anymore */
                #TransactionList table, #TransactionList thead, #TransactionList tbody, #TransactionList th, #TransactionList td, #TransactionList tr {
                    display: block;
                    text-align: left !important;
                }

                    /* Hide table headers (but not display: none;, for accessibility) */
                    #TransactionList thead tr {
                        left: -9999px;
                        position: absolute;
                        top: -9999px;
                    }

                #TransactionList tr {
                    border: 1px solid #ccc;
                }

                #TransactionList td:nth-of-type(1):before {
                    content: "PO Number :";
                    font-weight: bold;
                }

                #TransactionList td:nth-of-type(2):before {
                    content: "PO Date :";
                    font-weight: bold;
                }

                #TransactionList td:nth-of-type(3):before {
                    content: "PO Amount :";
                    font-weight: bold;
                }

                #TransactionList td:nth-of-type(4):before {
                    content: "Vendor :";
                    font-weight: bold;
                }

                #TransactionList td:nth-of-type(5):before {
                    content: "PO Description :";
                    font-weight: bold;
                }

                #TransactionList td:nth-of-type(6):before {
                    content: "Created By :";
                    font-weight: bold;
                }

                #TransactionList td:nth-of-type(7):before {
                    content: "Status :";
                    font-weight: bold;
                }

                #TransactionList td:nth-of-type(8):before {
                    content: "Action :";
                    font-weight: bold;
                }
            }
            /* Smartphones (portrait and landscape) ----------- */
        </style>
        <div id="resize_wrapper">
            <table id="TransactionList" class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>PO Number</th>
                        <th>PO Date</th>
                        <th>PO Amount</th>
                        <th>Vendor</th>
                        <th>PO Description</th>
                        <th>Created By</th>
                        <th>Status</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr class="handicon @if (item.VendorName == Check)
                                        {
                                            @item.VendorName.Replace(" ", string.Empty);
                                        }">
                            <td onclick="getTransaction(@item.Id)">
                                @if (!string.IsNullOrWhiteSpace(item.FileId))
                                {
                                    <button title="Download Attachment" type="button" class="btn btn-xs btn-warning" onclick="DownloadAttachemnt('@item.FileId')">
                                        <b class="fa fa-paperclip"></b>
                                    </button>
                                }
                                @Html.DisplayFor(model => item.BillNo)
                            </td>
                            <td onclick="getTransaction(@item.Id)" class="text-center">
                                @Html.DisplayFor(model => item.BillDate)
                            </td>
                            <td class="text-right">
                                <a class="handicon" onclick="getPODetailsOnNewWindow(@item.Id, 'PurchaseOrder')">
                                    <span class="@Session["Currency"].ToString() currencysize"></span>
                                    @Html.DisplayFor(model => item.TotalAmount)
                                </a>
                            </td>
                            <td onclick="getTransaction(@item.Id)" title="@item.VendorName">
                                @if (!string.IsNullOrWhiteSpace(item.VendorName))
                                {
                                    if (item.VendorName.Length > 30)
                                    {
                                        @item.VendorName.Substring(0, 30)
                                    }
                                    else
                                    {
                                        @item.VendorName
                                    }
                                }
                            </td>
                            <td onclick="getTransaction(@item.Id)" title="@item.PoRemarks">
                                @if (!string.IsNullOrWhiteSpace(item.PoRemarks))
                                {
                                    if (item.PoRemarks.Length > 20)
                                    {
                                        @item.PoRemarks.Substring(0, 20)
                                    }
                                    else
                                    {
                                        @item.PoRemarks
                                    }
                                }
                            </td>
                            <td onclick="getTransaction(@item.Id)" title="@item.CreatedByName">
                                @if (!string.IsNullOrWhiteSpace(item.CreatedByName))
                                {
                                    if (item.CreatedByName.Length > 15)
                                    {
                                        @item.CreatedByName.Substring(0, 15)
                                    }
                                    else
                                    {
                                        @item.CreatedByName
                                    }
                                }
                            </td>
                            <td onclick="getTransaction(@item.Id)" class="text-center">@Html.DisplayFor(model => item.Status)</td>
                            <td>
                                @if (item.Status != "Closed")
                                {
                                    <a href="#" onclick="createbillToPO(@item.Id, @item.VendorId, '@item.VendorName',@item.CostCenterId)">Create Bill</a>
                                }
                            </td>
                        </tr>
                    }

                </tbody>
            </table>
            <input value="@Model.Sum(a => a.TotalAmount).ToString("#,##0")" id="totAmtHide" type="hidden" />
        </div>
    </div>
</div>
<script>
    function createbillToPO(id, vid, v, CostCenterId) {
        var url = '';
        var menuCode = '';
        var data; 
        url = '@(Url.Action("Bill", "Expense"))';
        menuCode = 'PUROD';
        data = { id: 0, menuCode: menuCode, poiDs: id, vendorName: v, vID: vid, costCenterId :CostCenterId };
        $("#POlinkedPopUp").modal('toggle');
        $("div").removeClass("content");
        $(".hideSearchPanel").hide();
        getAjaxCall(url, data, 'TransactionDetail');
    }
    JQueryDatatable('TransactionList', 'FormView');
    function getTransaction(id) {
        createNewRecord(id);
    }

    $("#totPay").empty().html($("#totAmtHide").val());

    function DownloadAttachemnt(fileId) {
        location.href ='@(Url.Action("DownloadFile", "ImportAndExport"))?fileUploadID='+ fileId;
    }

    function getPODetailsOnNewWindow(id, screenType) { 
        window.open('@(Url.Action("Index", "PurchaseOrder"))?menuCode=PUROD&id=' + id + '&IsNewWindow=true&screenType=' + screenType);
    }
</script>