cvt.officebau.com/Controllers/TDSConfigurationController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using cvt.officebau.com.Utilities;
using cvt.officebau.com.Services;
using cvt.officebau.com.ViewModels;

namespace cvt.officebau.com.Controllers
{
    [SessionExpire]
    public class TDSConfigurationController : Controller
    {
        #region Variables

        private readonly TdsConfigurationRepository _tdsConfigurationRepository = new TdsConfigurationRepository();

        #endregion Variables

        #region TDS Configuration

        public ActionResult TdsConfiguration()
        {
            Utility.SetSession("MenuRetention", "APPLICATIONCONFIGURATION");
            Utility.SetSession("SubMenuRetention", "TDSCONFIGURATION");
             UtilityRepository track= new UtilityRepository(); track.TrackFormNavigation("TDS Configuration");

            RbsRepository rBsRepository = new RbsRepository();
            return View(rBsRepository.SearchMenuForConfiguration());
        }

        public ActionResult SearchTdsConfiguration()
        {
             UtilityRepository track= new UtilityRepository(); track.TrackFormNavigation("TDS Component Configuration");

            TdsConfigurationBo tdsConfigurationBo = new TdsConfigurationBo();
            MasterDataRepository masterDataRepository = new MasterDataRepository();

            tdsConfigurationBo.FinancialYearList = masterDataRepository.SearchMasterDataDropDown("FinancialYear", string.Empty);
            UtilityRepository utilityRepository = new UtilityRepository();
            tdsConfigurationBo.FinancialYearList = utilityRepository.GetFinancialYearText();
            tdsConfigurationBo.RegionList = masterDataRepository.GetRegionDropDownDependOnEmployee(Utility.UserId());
            return PartialView(tdsConfigurationBo);
        }

        public ActionResult TdsConfigurationList(int fyid, int regionId)
        {
            TdsConfigurationBo tdsConfigurationBo = new TdsConfigurationBo
            {
                FinancialYearId = fyid,
                RegionId = regionId
            };

            return PartialView(_tdsConfigurationRepository.SearchTdsLimitConfiguration(tdsConfigurationBo));
        }

        public ActionResult ManageTdsConfiguration(int id)
        {
            TdsConfigurationBo tdsConfigurationBo = _tdsConfigurationRepository.GetTdsLimitConfiguration(id);
            MasterDataRepository masterDataRepository = new MasterDataRepository();
            tdsConfigurationBo.FinancialYearList = masterDataRepository.SearchMasterDataDropDown("FinancialYear", string.Empty);
            UtilityRepository utilityRepository = new UtilityRepository();
            tdsConfigurationBo.FinancialYearList = utilityRepository.GetFinancialYearText();
            tdsConfigurationBo.SectionList = masterDataRepository.SearchMasterDataDropDown("TDSSection", string.Empty);
            tdsConfigurationBo.RegionList = masterDataRepository.GetRegionDropDownDependOnEmployee(Utility.UserId());
            return PartialView(tdsConfigurationBo);
        }

        [HttpPost]
        public ActionResult ManageTdsConfiguration(TdsConfigurationBo tdsConfigurationBo)
        {
            RbsRepository rbsRepository = new RbsRepository();
            tdsConfigurationBo.MenuCode = MenuCode.TDSLimitConfiguration;

            bool hasAccess = rbsRepository.IsAuthorized(Utility.UserId(), tdsConfigurationBo.MenuCode, tdsConfigurationBo.Id == 0 ? "Save" : "Edit");
            if (tdsConfigurationBo.IsDeleted)
            {
                hasAccess = rbsRepository.IsAuthorized(Utility.UserId(), tdsConfigurationBo.MenuCode, "Delete");
            }

            if (!hasAccess)
            {
                return Json(Constants.UnAuthorizedAccess, JsonRequestBehavior.AllowGet);
            }

            return Json(_tdsConfigurationRepository.ManageTdsLimitConfiguration(tdsConfigurationBo), JsonRequestBehavior.AllowGet);
        }

        #endregion TDS Configuration

        #region TDS Configuration Payroll Components

        public ActionResult TdsConfigurationPayrollComponents()
        {
            Utility.SetSession("MenuRetention", "APPLICATIONCONFIGURATION");
            Utility.SetSession("SubMenuRetention", "CONFIGURATION");
             UtilityRepository track= new UtilityRepository(); track.TrackFormNavigation("TDS Configuration");

            TdsConfigurationBo tdsConfigurationBo = new TdsConfigurationBo();
            MasterDataRepository masterDataRepository = new MasterDataRepository();

            tdsConfigurationBo = _tdsConfigurationRepository.GetTdsConfiguration();
            tdsConfigurationBo.PayrollComponentList = masterDataRepository.SearchMasterDataDropDown("Pay_PayrollCompontents", string.Empty);
            return PartialView(tdsConfigurationBo);
        }

        [HttpPost]
        public JsonResult SubmitTdsConfiguration(TdsConfigurationBo tdsConfigurationBo)
        {
            List<TdsConfigurationBo> list = new List<TdsConfigurationBo>();
            if (tdsConfigurationBo != null)
            {
                TdsConfigurationBo tdsConfigurationListBo = new TdsConfigurationBo();
                list.Add(tdsConfigurationListBo);
                list[0].Values = "CTC";
                list[0].PayrollComponentID = tdsConfigurationBo.CTCComponentID;

                tdsConfigurationListBo = new TdsConfigurationBo();
                list.Add(tdsConfigurationListBo);
                list[1].Values = "BASIC";
                list[1].PayrollComponentID = tdsConfigurationBo.BasicComponentID;

                //tdsConfigurationListBo = new TdsConfigurationBo();
                //list.Add(tdsConfigurationListBo);
                //list[2].Values = "MEDICAL";
                //list[2].PayrollComponentID = tdsConfigurationBo.MedicalComponentID;

                //tdsConfigurationListBo = new TdsConfigurationBo();
                //list.Add(tdsConfigurationListBo);
                //list[3].Values = "CONVEYANCE";
                //list[3].PayrollComponentID = tdsConfigurationBo.ConveyanceComponentID;

                tdsConfigurationListBo = new TdsConfigurationBo();
                list.Add(tdsConfigurationListBo);
                list[2].Values = "HRA";
                list[2].PayrollComponentID = tdsConfigurationBo.HRAComponentID;
            }

            if (tdsConfigurationBo != null)
            {
                tdsConfigurationBo = _tdsConfigurationRepository.ManageTdsConfiguration(list);
            }
            return Json(tdsConfigurationBo.UserMessage, JsonRequestBehavior.AllowGet);
        }

        #endregion TDS Configuration
    }
}

cvt.officebau.com/Views/TDSConfiguration/ManageTdsConfiguration.cshtml
@model TdsConfigurationBo
<div class="">
    <div class="box box-info">
        <div class="box-header with-border clickable handicon margin-bottom">
            <div class="box-title">
                <span class="pull-left ">
                    <i class="glyphicon  glyphicon-triangle-bottom"></i>
                </span> &nbsp;&nbsp; TDS Limit Configuration
            </div>
        </div>
        <div class="box-body">
            @using (Html.BeginForm("ManageTdsConfiguration", "TDSConfiguration", FormMethod.Post, new { @class = "form-horizontal", id = "ManageTDSConfigurationID" }))
            {
                @Html.HiddenFor(m => m.Id)
                @Html.HiddenFor(model => model.IsDeleted, new { id = "asdasds" })
                <div class="form-group">
                    <label class="col-md-4 control-label">Region<b class="Mandatory"> *</b></label>
                    <div class="col-md-3 employeeID">
                        @Html.DropDownListFor(m => m.RegionId, new SelectList(Model.RegionList, "Value", "Text"), new { @class = "form-control", id = "RegionID" })
                        @Html.ValidationMessageFor(model => model.RegionId, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-4 control-label">Financial Year<b class="Mandatory"> *</b></label>
                    <div class="col-md-3 employeeID">
                        @Html.DropDownListFor(m => m.FinancialYearId, new SelectList(Model.FinancialYearList, "Value", "Text"), new { @class = "form-control", id = "FinancialYearID" })
                        @Html.ValidationMessageFor(model => model.FinancialYearId, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-4 control-label">Section<b class="Mandatory"> *</b></label>
                    <div class="col-md-3">
                        @Html.DropDownListFor(model => model.SectionId, new SelectList(Model.SectionList, "Value", "Text"), new { @class = "form-control", id = "SectionID" })
                        @Html.ValidationMessageFor(model => model.SectionId, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-4 control-label">Ceiling Amount<b class="Mandatory"> *</b></label>
                    <div class="col-md-3">
                        @Html.TextBoxFor(model => model.Limit, string.Format("{0:0.00}", Model.Limit), new { @class = "form-control", id = "Limit" })
                        @Html.ValidationMessageFor(model => model.Limit, "", new { @class = "text-danger" })
                    </div>
                </div>
            }
        </div>
    </div>
</div>
<footer class="main-footer navbar-fixed-bottom">
    <div class="row">


        <div class="col-md-6 hidemodified">
            @if (Model.Id != 0)
            {
                <span style="padding: 10px;"> Mod. By&nbsp;&nbsp;<b>@Model.ModifiedByName</b>&nbsp;&nbsp;on&nbsp;&nbsp;<b>@Html.DisplayFor(model => model.ModifiedOn)</b></span>
            }
        </div>
        <div class="col-md-6 col-xs-12 text-right">
            @if (Model.Id != 0)
            {
                <button type="button" title="Update" class="btn btn-primary btn-md btn-fill " onclick="SaveTDSConfigure()" tabindex="0">
                    <i class="fa fa-floppy-o"></i> Update
                </button>
                <button type="button" value="Delete" title="Delete" data-toggle="modal" data-target="#myModal" class="btn btn-md flat-warning alert-confirm btn-danger btn-fill waves-effect">
                    <i class="fa fa-trash"></i> Delete
                </button>
            }
            else
            {
                <button type="button" title="Save & New" class="btn btn-info btn-md btn-fill " onclick="saveandnewTDSConfigure()" tabindex="0">
                    Save & New
                </button>
                <button type="button" title="Save" class="btn btn-primary btn-md btn-fill " onclick="SaveTDSConfigure()" tabindex="0">
                    <i class="fa fa-floppy-o"></i> Save
                </button>
            }
            <button type="button" value="Cancel" title="Cancel" class="btn btn-md btn-success btn-fill waves-effect" onclick="cancelTDSConfigure()">
                <i class="fa fa-refresh"></i> Cancel
            </button>
        </div>
    </div>
</footer>
<div class="modal fade" id="myModal" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="false">×</button>
                <h4 class="modal-title">Delete Confirmation</h4>
            </div>
            <div class="container"></div>
            <div class="modal-body">
                Are you sure want to Delete ?
            </div>
            <div class="modal-footer">
                <a href="#" title="No" data-dismiss="modal" class="btn btn-md">No</a>
                <a href="#" title="Yes" onclick="DeleteTDSConfigure()" class="btn btn-danger btn-md">Yes</a>
            </div>
        </div>
    </div>
</div>
<script>

    $(document).ready(function() {
        if (@Model.Id == 0) {
            $("#Limit").val('');
        } else {
            Common.getLocalDateTimeFromUTC();
        }
    });
    $('#myModal').draggable();

    function SaveTDSConfigure() {
        var $form = $('#ManageTDSConfigurationID');
        var validator = $form.data("validator");
        if (!validator || !$form.valid()) {
            return;
        }
        ajaxindicatorstart();
        $.post($("#ManageTDSConfigurationID").attr("action"),
            $("#ManageTDSConfigurationID").serialize(),
            function(data) {
                if (data.indexOf("Successfully") !== -1) {
                    $.notify({
                        message: data
                    },
                        {
                            type: 'success',
                            timer: 4000

                        });
                    setTimeout(function() {
                        cancelTDSConfigure();
                    },
                        1000);
                } else {
                    $.notify({
                        message: data
                    },
                        {
                            type: 'warning',
                            timer: 4000
                        });
                }
            });
        ajaxindicatorstop();
    }

    function saveandnewTDSConfigure() {
        var $form = $("#ManageTDSConfigurationID");
        var validator = $form.data("validator");
        if (!validator || !$form.valid()) {
            return;
        }
        ajaxindicatorstart();
        $.ajax({ 
            url: '@(Url.Action("ManageTdsConfiguration", "TDSConfiguration"))',
            type: 'POST',
            data: $("#ManageTDSConfigurationID").serialize(),
            success: function(data) {
                if (data.indexOf("Successfully") !== -1) {
                    $.notify({
                        message: data
                    },
                        {
                            type: 'success',
                            timer: 4000
                        });
                    CreateTDSConfig(0);
                } else {
                    $.notify({
                        message: data
                    },
                        {
                            type: 'warning',
                            timer: 4000
                        });
                }
            },
            error: function(data) {
            }
        });
        ajaxindicatorstop();
    }

    function DeleteTDSConfigure() {
        $("#asdasds").val(true);
        $.ajax({ 
            url: '@(Url.Action("ManageTdsConfiguration", "TDSConfiguration"))',
            type: 'POST',
            cache: false,
            data: $("#ManageTDSConfigurationID").serialize(),
            success: function(data) {
                if (data.indexOf("Successfully") !== -1) {
                    $.notify({
                        message: data
                    },
                        {
                            type: 'success',
                            timer: 4000
                        });

                } else {
                    $.notify({
                        message: data
                    },
                        {
                            type: 'warning',
                            timer: 4000
                        });
                }
                setTimeout(function() {
                    cancelTDSConfigure();
                },
                    1000);
                $("#myModal").modal('hide');
            },
            error: function(data) {
                $("#ErrorPopup").modal('show');
            }
        });
    }
</script>
@Scripts.Render("~/bundles/jqueryval")

cvt.officebau.com/Views/TDSConfiguration/SearchTdsConfiguration.cshtml
@model TdsConfigurationBo
<html>
<head>
    <title>
        OfficeBAU - TDS Component Configuration
    </title>
</head>
<body>
    <section class="content-header1 margin-bottom">
        <h1>
            TDS Component Configuration
            <a onclick="backToConfig()" title="Back to Configuration" class="btn btn-primary pull-right handicon pull-right backBtn">
                <span class="fa fa-backward"></span> <span class="hidemodified">Back </span>
            </a>
            <button type="button" class="btn btn-primary pull-right margin-r-5 hidesearch" title="Create New TDS Limit Configuration" onclick="CreateTDSConfig(0)"><i class="fa fa-plus" aria-hidden="true"></i> Create New</button>
            @if (Session["IsExcelDownload"].ToString() == "1" || Session["IsExcelDownload"].ToString().ToUpper() == "TRUE")
            {
                <button onclick="TDSLimitConfigExcel()" id="Excelshow" class="btn btn-md btn-info pull-right margin-r-5 hidesearch hidemodified" title="Export" style="margin-left: 5px">
                    <span class="fa fa-file-excel-o fa-lg"></span>
                </button>
            }
        </h1>
    </section>
    <section class="">
        <div class="row hidesearch" id="EditTDSConfig">
            <div class="col-md-12">
                <div class="box box-warning" id="accordion">
                    <div class="box-title">
                        <div class="box-header with-border bottom-border accordion-toggle handicon" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" onclick="gridResize()">
                            <span class="fa fa-search"></span><strong> Search</strong><i class="indicator glyphicon glyphicon-chevron-up pull-right"></i>
                        </div>
                    </div>
                    <div id="collapseOne" class="panel-collapse collapse in">
                        <div class="panel-body">
                            <form class="form-horizontal">
                                <div class="">
                                    @Html.HiddenFor(model => model.FinancialYearId)
                                    @Html.HiddenFor(model => model.IsDeleted, new { id = "isDeleted" })
                                    <div class="col-md-4">
                                        <div class="form-groupsecond">
                                            <label class="col-md-6 control-label">
                                                Region<b class="Mandatory"> *</b>
                                            </label>
                                            <div class="col-md-6">
                                                @if (Model.RegionList.Count == 2)
                                                {
                                                    Model.RegionId = Convert.ToInt32(Model.RegionList[1].Value);
                                                }
                                                @Html.DropDownListFor(model => Model.RegionId, Model.RegionList, new { @class = "form-control", id = "RegionID", tabindex = "0" })
                                                <span class="hide text-danger" id="RegionIDvalid">Please select Region.</span>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="form-groupsecond">
                                            <label class="col-md-6 control-label">
                                                Financial Year<b class="Mandatory"> *</b>
                                            </label>
                                            <div class="col-md-6">
                                                @Html.DropDownListFor(model => model.FinancialYearId, Model.FinancialYearList, new { @class = "form-control", tabindex = "1", id = "searchFinancialYear" })
                                                <span class="hide text-danger" id="FinancialYearIDvalid">Please select Financial Year.</span>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="form-groupsecond margin-t-3">
                                            <div class="col-md-8 col-md-offset-2">
                                                <button type="button" title="Search" id="searchbtn" class="btn btn-primary btn-md btn-fill" onclick="searchTDSConfig()" tabindex="0">
                                                    <span class="fa fa-search"></span> Search
                                                </button>
                                                <button type="button" title="Reset" tabindex="0" class="btn btn-danger btn-md btn-fill" onclick="ClearTDSSearch()">
                                                    <span class="fa fa-undo"></span> Reset
                                                </button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div id="TDSConfigurationListID"></div>
    </section>
    <script>
        $("#Excelshow").hide();

        function TDSLimitConfigExcel() {
            var fyid = $("#searchFinancialYear").val() === null ? 0 : $("#searchFinancialYear").val();
            var regionId = $("#RegionID").val() === "" ? 0 : $("#RegionID").val(); 
            location.href = '@(Url.Action("TdsLimitConfiguration", "ExcelExport"))?formName=TDS_Limit_Configuration' +
                "&year=" +
                fyid +
                "&regionId=" +
                regionId;
        }

        function searchTDSConfig() {
            $("#resize_wrapper").empty();
            $("#TDSConfigurationListID").empty();
            if ($("#RegionID").val() === '' || $("#searchFinancialYear").val() === '') {
                if ($("#RegionID").val() === '') {
                    $("#RegionIDvalid").removeClass('hide');
                }
                if ($("#searchFinancialYear").val() === '') {
                    $("#FinancialYearIDvalid").removeClass('hide');
                }
            } else {
                $("#FinancialYearIDvalid").addClass('hide');
                $("#RegionIDvalid").addClass('hide');
                $("#resize_wrapper").empty();
                $("#TDSConfigurationListID").empty();
                $("#TDSConfigurationListID").addClass("loaders");
                $("#Excelshow").show();
                $.ajax({ 
                    url: '@(Url.Action("TDSConfigurationList", "TDSConfiguration"))',
                    type: 'GET',
                    cache: false,
                    data: { fyid: $("#searchFinancialYear").val(), regionId: $("#RegionID").val() },
                    success: function (data) {
                        $("#TDSConfigurationListID").html(data);
                        $("#TDSConfigurationListID").removeClass("loaders");
                    },
                    error: function (data) {
                        $("#ErrorPopup").modal('show');
                    }
                });
            }
        }

        function ClearTDSSearch() {
            $("#searchFinancialYear").val('');
            $("#RegionID").val('');
            $("#Excelshow").hide();
        }

        $('#accordion').on('hidden.bs.collapse',
            function () {
                $(".indicator").addClass('glyphicon-chevron-up').removeClass('glyphicon-chevron-down');
            });
        $('#accordion').on('shown.bs.collapse',
            function () {
                $(".indicator").addClass('glyphicon-chevron-down').removeClass('glyphicon-chevron-up');
            });

        function CreateTDSConfig(id) {
            $("#EditTDSConfig").hide();
            $(".backBtn").hide();
            $("#resize_wrapper").empty();
            $("#resize_wrapper").addClass("loaders");
            $.ajax({ 
                url: '@(Url.Action("ManageTdsConfiguration", "TDSConfiguration"))',
                type: 'GET',
                cache: false,
                data: { id: id },
                success: function (data) {
                    $(".hidesearch").hide();
                    $("#TDSConfigurationListID").empty().html(data);
                    $("#resize_wrapper").removeClass("loaders");
                },
                error: function (data) {
                    $("#ErrorPopup").modal('show');
                }
            });
        }

        function cancelTDSConfigure() { 
            GetDetails('@(Url.Action("SearchTdsConfiguration", "TDSConfiguration"))');
        }
    </script>
</body>
</html>

cvt.officebau.com/Views/TDSConfiguration/TdsConfiguration.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model List<RbsMenuBo>
@{
    var count = 1;
    var headerColor = string.Empty;
    string[] color = { "#8bc34a", "#009688", "#0fa8e4", "#af41f4", "#f44182", "#ffc107" };
}
<html>
<head>
    <title>
        OfficeBAU - TDS Configuration
    </title>
    <style>
        .content {
            overflow: auto;
        }

        .cardcontainer {
            background-color: inherit;
            padding: 10px 40px;
        }

        .cardcontent {
            background-color: white;
            box-shadow: 5px 5px #88888880;
        }

        @@media screen and (max-width: 600px) {
            .cardcontainer {
                padding: 0;
                padding-right: 25px;
                width: 100%;
            }

                .cardcontainer::before {
                    border: medium solid white;
                    border-color: transparent white transparent transparent;
                    border-width: 10px 10px 10px 0;
                    left: 60px;
                }
        }

        .branch ul li a {
            color: #3c8dbc;
            font-weight: bold;
            text-decoration: underline;
        }

            .branch ul li a:hover {
                color: black;
            }

        .branch ul li span {
            color: black;
        }

        .increasefont {
            font-size: 20px;
        }
    </style>
</head>
<body>
    <link rel="stylesheet" href="~/plugins/treeView/treeView.css" />
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <div class="content hideSearchPanel" id="bindreport">
        <div class="row">
            <div class="col-xs-12">
                <div id="">
                    <div class="cardcontent" style="padding: 10px 10px; text-align: center; */">
                        <h4 style="font-weight: 600;">
                            <span id="spnHeaderName"></span>
                        </h4>
                    </div>
                    <div class="">
                        <div class="cardcontainer col-md-12">
                            @foreach (var group in Model.GroupBy(item => item.Module))
                            {
                                foreach (var group1 in group.GroupBy(item => item.ModuleGroup))
                                {
                                    count++;
                                    if (count == 6)
                                    {
                                        count = 0;
                                    }
                                    headerColor = color[count];
                                    <div class="col-md-6" style="margin-top: 15px;">
                                        <div class="cardcontent card" style="background-color: white">
                                            <ul class="treeopen">
                                                <li>
                                                    <a class="increasefont" style="color: @headerColor; font-weight: 600;">
                                                        <span class="fa fa-minus-circle"></span>
                                                        @Html.Encode(group1.Key)
                                                    </a><br />
                                                    <ul>
                                                        @foreach (var item in group1)
                                                        {
                                                        <li>                                                            
                                                            <a href="#" onclick="GetDetails('@(Url.Action(item.Action, item.Controller))')">
                                                                @item.Menu
                                                            </a>
                                                        </li>
                                                        }
                                                    </ul>
                                                </li>
                                            </ul>
                                        </div>
                                    </div>
                                }
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script>

        function GetDetails(url) {
            ajaxindicatorstart();
            $.ajax({
                url: url,
                type: 'GET',
                cache: false,
                data: {},
                success: function (data) {
                    $("#bindreport").html(data);
                    ajaxindicatorstop();
                },
                error: function (data) {
                    alert(data);
                }
            });
        }

        $(document).ready(function () {
            $('.treeopen').treed();
        });
        setTimeout(function () {
            gridResize();
        },
            400);
        $.fn.extend({
            treed: function (o) {
                var tree = $(this);
                tree.addClass("tree");
                tree.find('li').has("ul").each(function () {
                    var branch = $(this);
                    branch.addClass('branch');
                    branch.closest('ul').click();
                });
            }
        });
        $(document).ready(function () {
            calcCardHeight();
            setTimeout(function () { setCardHeight(_height) }, 100);
        });
        var _height = 0;

        function setCardHeight(_height) {
            $('.card').each(function () {
                $(this).css("height", _height);
            }
            );
        }

        function calcCardHeight() {
            $('.card').each(function () {
                var thisheight = parseFloat($(this).height());
                if (_height < thisheight) {
                    _height = thisheight;
                }
            });
        }
    </script>
    @Scripts.Render("~/bundles/jqueryval")
</body>
</html>