cvt.officebau.com/Controllers/EmployeeOffBoardProcessController.cs
using cvt.officebau.com.Utilities;
using cvt.officebau.com.Services;
using cvt.officebau.com.ViewModels;
using System;
using System.Web.Mvc;

namespace cvt.officebau.com.Controllers
{
    [SessionExpire]
    public class EmployeeOffBoardProcessController : Controller
    {
        #region Variables

        private EmployeeOffBoardBo _employeeOffBoardBo = new EmployeeOffBoardBo();
        private readonly EmployeeOffBoardProcessRepository _employeeOffBoardProcessRepository = new EmployeeOffBoardProcessRepository();

        #endregion Variables

        #region OffBoard Request

        public ActionResult OffBoardRequest(string menuCode)
        {
            Utility.SetSession("MenuRetention", "EXITPROCESS");
            Utility.SetSession("SubMenuRetention", "OFFBOARDREQUEST");
             UtilityRepository track= new UtilityRepository(); track.TrackFormNavigation("Employee Offboard Request");

            LeaveManagementRepository leaveManagementRepository = new LeaveManagementRepository();

            _employeeOffBoardBo.EmployeeId = Utility.UserId();
            string id = _employeeOffBoardProcessRepository.GetOffboardRequestId(Utility.UserId());

            if (!string.IsNullOrWhiteSpace(id))
            {
                _employeeOffBoardBo = _employeeOffBoardProcessRepository.GetOffBoardRequest(Convert.ToInt32(id));
            }
            else
            {
                _employeeOffBoardBo.Approver = leaveManagementRepository.GetApprover(Utility.UserId(), "Name");
                _employeeOffBoardBo.ApproverId = Convert.ToInt32(leaveManagementRepository.GetApprover(Utility.UserId(), "ID"));
            }

            return View(_employeeOffBoardBo);
        }

        [HttpPost]
        public ActionResult OffBoardRequest(EmployeeOffBoardBo employeeOffBoardBo)
        {
            employeeOffBoardBo.MenuCode = MenuCode.EmployeeOffBoardRequest;
            string message = string.Empty;
            RbsRepository rbsRepository = new RbsRepository();
            employeeOffBoardBo.ModifiedBy = Utility.UserId();
            employeeOffBoardBo.EmployeeId = Utility.UserId();

            bool hasAccess = rbsRepository.IsAuthorized(Utility.UserId(), employeeOffBoardBo.MenuCode, "Save");

            if (!hasAccess)
            {
                return Json(Constants.UnAuthorizedAccess, JsonRequestBehavior.AllowGet);
            }

            switch (employeeOffBoardBo.Operation.ToUpper())
            {
                case Operations.Insert:
                    message = _employeeOffBoardProcessRepository.ManageOffBoardRequest(employeeOffBoardBo);
                    break;

                case Operations.Update:
                    message = _employeeOffBoardProcessRepository.ManageOffBoardRequest(employeeOffBoardBo);
                    break;

                case Operations.Withdraw:
                    employeeOffBoardBo.IsDeleted = true;
                    employeeOffBoardBo.EmployeeId = Utility.UserId();
                    message = _employeeOffBoardProcessRepository.WithdrawOffBoardRequest(employeeOffBoardBo);
                    break;

                case Operations.Delete:
                    message = _employeeOffBoardProcessRepository.DeleteOffBoardRequest(employeeOffBoardBo);
                    break;
            }

            return Json(message, JsonRequestBehavior.AllowGet);
        }

        public ActionResult OffBoardWithdrawHistory(int employeeId)
        {
            _employeeOffBoardBo.EmployeeId = employeeId;
            _employeeOffBoardBo.DomainId = Utility.DomainId();

            return PartialView(_employeeOffBoardProcessRepository.GetOffBoardHistory(employeeId));
        }

        #endregion OffBoard Request

        #region OffBoard Approve

        public ActionResult SearchOffBoardApprove(string menuCode)
        {
            Utility.SetSession("MenuRetention", "EXITPROCESS");
            Utility.SetSession("SubMenuRetention", "OFFBOARDAPPROVAL");
             UtilityRepository track= new UtilityRepository(); track.TrackFormNavigation("Employee Offboard Approval");

            MasterDataRepository masterDataRepository = new MasterDataRepository();

            _employeeOffBoardBo.ApproverId = Utility.UserId();
            _employeeOffBoardBo.StatusList = masterDataRepository.SearchMasterDataDropDown("Status", "OffBoard");
            _employeeOffBoardBo.StatusId = _employeeOffBoardProcessRepository.GetStatusId("OffBoard", "Initiated");
            return View(_employeeOffBoardBo);
        }

        public ActionResult OffBoardApproveList(EmployeeOffBoardBo employeeOffBoardBo)
        {
            employeeOffBoardBo.UserId = Utility.UserId();
            employeeOffBoardBo.DomainId = Utility.DomainId();
            return PartialView(_employeeOffBoardProcessRepository.SearchOffBoardApproval(employeeOffBoardBo));
        }

        public ActionResult OffBoardApprove(int id)
        {
            MasterDataRepository masterDataRepository = new MasterDataRepository();

            _employeeOffBoardBo = _employeeOffBoardProcessRepository.GetOffBoardRequest(id);
            _employeeOffBoardBo.ApproverList = masterDataRepository.SearchEmpDropDownForCode("HR Manager", 0);
            _employeeOffBoardBo.MenuCode = MenuCode.EmployeeOffBoardApprove;
            return PartialView(_employeeOffBoardBo);
        }

        [HttpPost]
        public ActionResult OffBoardApprove(int id, string status, string remarks, int? hrApproverId, DateTime? tentativeRelievingDate, int employeeId, DateTime? initiatedDate, DateTime? relievingDate)
        {
            RbsRepository rbsRepository = new RbsRepository();
            int approverId = Utility.UserId();
            int domainId = Utility.DomainId();
            bool hasAccess = rbsRepository.IsAuthorized(Utility.UserId(), Utility.GetSession("MenuID"), "Edit");
            if (!hasAccess)
            {
                return Json(Constants.UnAuthorizedAccess, JsonRequestBehavior.AllowGet);
            }

            return Json(_employeeOffBoardProcessRepository.ApproveOffBoardRequest(id, status, remarks, approverId, domainId, hrApproverId, tentativeRelievingDate, employeeId, initiatedDate, relievingDate), JsonRequestBehavior.AllowGet);
        }

        #endregion OffBoard Approve

        #region HR Approval

        public ActionResult SearchOffBoardHrApprove(string menuCode)
        {
            Utility.SetSession("MenuRetention", "EXITPROCESS");
            Utility.SetSession("SubMenuRetention", "EXITPROCESS");

            MasterDataRepository masterDataRepository = new MasterDataRepository();

             UtilityRepository track= new UtilityRepository(); track.TrackFormNavigation("Employee Offboard Approval - HR");
            _employeeOffBoardBo.HrApproverId = Utility.UserId();
            _employeeOffBoardBo.StatusList = masterDataRepository.SearchMasterDataDropDown("Status", "OffBoard");
            _employeeOffBoardBo.StatusId = _employeeOffBoardProcessRepository.GetStatusId("OffBoard", "Pending");
            return View(_employeeOffBoardBo);
        }

        public ActionResult OffBoardHrApproveList(EmployeeOffBoardBo employeeOffBoardBo)
        {
            employeeOffBoardBo.UserId = Utility.UserId();
            employeeOffBoardBo.DomainId = Utility.DomainId();
            return PartialView(_employeeOffBoardProcessRepository.SearchOffBoardHrApproval(employeeOffBoardBo));
        }

        public ActionResult OffBoardHrApprove(int id, int employeeId)
        {
            MasterDataRepository masterDataRepository = new MasterDataRepository();
            _employeeOffBoardBo.MenuCode = MenuCode.EmployeeOffBoardHRApproval;

            _employeeOffBoardBo = _employeeOffBoardProcessRepository.GetOffBoardHrApprove(id);
            ViewData["CompanyAsset"] = _employeeOffBoardProcessRepository.SearchCompanyAssetDetail(_employeeOffBoardBo);

            EmployeeOffBoardBo employeeExitBo = _employeeOffBoardProcessRepository.GetExitInterviewDetail(id);
            employeeExitBo.RelivingReasonList = masterDataRepository.SearchMasterDataDropDown("ExitReason", string.Empty);
            ViewData["ExitDetails"] = employeeExitBo;
            return PartialView(_employeeOffBoardBo);
        }

        public ActionResult CompanyAssetsDetails(int employeeId, int offboardProcessID)
        {
            _employeeOffBoardBo.EmployeeId = employeeId;
            _employeeOffBoardBo.Id = offboardProcessID;
            return PartialView(_employeeOffBoardProcessRepository.SearchCompanyAssetDetail(_employeeOffBoardBo));
        }

        public ActionResult AssetsReturnedDetails(EmployeeOffBoardBo employeeOffBoardBo)
        {
            return PartialView(_employeeOffBoardProcessRepository.SearchCompanyAssetDetail(employeeOffBoardBo));
        }

        public ActionResult ReturnedDetails(int id)
        {
            CompanyAssetsBo companyAssetsBo = new CompanyAssetsBo();
            if (id != 0)
            {
                companyAssetsBo = _employeeOffBoardProcessRepository.GetReturnDetail(id);
            }

            return PartialView(companyAssetsBo);
        }

        public ActionResult RemarksDetails(int id)
        {
            CompanyAssetsBo companyAssetsBo = new CompanyAssetsBo();
            if (id != 0)
            {
                companyAssetsBo = _employeeOffBoardProcessRepository.GetReturnDetail(id);
            }

            return PartialView(companyAssetsBo);
        }

        [HttpPost]
        public ActionResult ReturnedDetails(CompanyAssetsBo companyAssetsBo)
        {
            _employeeOffBoardBo.UserId = Utility.UserId();
            _employeeOffBoardBo.DomainId = Utility.DomainId();
            return Json(_employeeOffBoardProcessRepository.UpdateReturnedDetails(companyAssetsBo), JsonRequestBehavior.AllowGet);
        }

        public ActionResult ExitInterviewDetails(int id, int employeeId)
        {

cvt.officebau.com/Views/EmployeeOffBoardProcess/AssetsClearanceList.cshtml
@model IList<EmployeeOffBoardBo>

<style>
    @@media only screen and (max-width: 760px), (min-device-width: 768px) and (max-device-width: 1024px) {
        table, thead, tbody, th, td, tr { display: block; }

        thead tr {
            left: -9999px;
            position: absolute;
            top: -9999px;
        }

        tr { border: 1px solid #ccc; }

        td:nth-of-type(1):before {
            content: "Employee No :";
            font-weight: bold;
        }

        td:nth-of-type(2):before {
            content: "Employee Name :";
            font-weight: bold;
        }

        td:nth-of-type(3):before {
            content: "Business Unit :";
            font-weight: bold;
        }


        td:nth-of-type(4):before {
            content: "Approver Name :";
            font-weight: bold;
        }

        td:nth-of-type(5):before {
            content: "Approved On :";
            font-weight: bold;
        }

        td:nth-of-type(6):before {
            content: "Status :";
            font-weight: bold;
        }
    }
</style>

<div class="row">
    <div class="col-xs-12">
        <div class="box box-primary">
            <div class="box-body">
                <div id="resize_wrapper">
                    <table class="table table-bordered table-striped" id="approvalTable">
                        <thead>
                        <tr>
                            <th>Employee No</th>
                            <th>Employee Name</th>
                            <th>Business Unit</th>
                            <th>Approver Name</th>
                            <th>Approved On</th>
                            <th>Status</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach (var item in Model)
                        {
                            var approvedDate = Convert.ToDateTime(item.ApprovedDate).ToString("dd-MMM-yyyy");
                            <tr class="handicon" onclick="GetAssetsClearanceList('@item.EmployeeId', '@item.EmployeeName', '@item.Code', '@item.Id')">
                                <td title="@item.Code">
                                    @item.Code
                                </td>
                                <td title="@item.EmployeeName">
                                    @item.EmployeeName
                                </td>
                                <td title="@item.BusinessUnitName">
                                    @item.BusinessUnitName
                                </td>
                                <td title="@item.ApproverName">
                                    @item.ApproverName
                                </td>
                                <td title="@approvedDate" class="text-center">
                                    @approvedDate
                                </td>
                                <td title="@item.AssetStatus">
                                    @item.AssetStatus
                                </td>
                            </tr>
                        }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    gridResize();
    $('#approvalTable').DataTable({
        "paging": true,
        "lengthChange": true,
        "lengthMenu": [[10, 25, 50, -1], [10, 25, 50, "All"]],
        "searching": true,
        "ordering": true,
        "info": true,
        "autoWidth": false,
        "aaSorting": [],
        pageResize: true
    });
    var _EMPNAME;
    var _EMPCODE;

    function GetAssetsClearanceList(employeeId, employeeName, empcode, offboardProcessID) {
        _EMPNAME = employeeName;
        _EMPCODE = empcode;
        $("#excelhide").hide();
        $("#resize_wrapper").empty();
        $("#resize_wrapper").addClass('loaders');
        $(".hidesearch").hide();
        $.ajax({ 
            url: '@(Url.Action("CompanyAssetsDetails", "EmployeeOffBoardProcess"))',
            type: 'GET',
            cache: false,
            data: { employeeId: employeeId, offboardProcessID: offboardProcessID},
            success: function(data) {
                setTimeout(function() {
                        $("#AssetsClearanceList").empty().html(data);
                        $("#resize_wrapper").removeClass('loaders');
                    },
                    500);
            },
            error: function(data) {
            }
        });
    }
</script>

cvt.officebau.com/Views/EmployeeOffBoardProcess/CompanyAssetsDetails.cshtml
@model IList<CompanyAssetsBo>

<div class="box box-primary">
    <div class="box-header with-border clickable handicon">
        <div class="box-title">
            <span class="pull-left ">
                <i class="glyphicon  glyphicon-triangle-bottom"></i>
            </span> &nbsp;&nbsp; Asset Clearance - <span id="Requestercode"></span> - <span id="Requestername"></span>
        </div>
    </div>
    <div class="box-body">
        <style>
            @@media only screen and (max-width: 760px), (min-device-width: 768px) and (max-device-width: 1024px) {
                table, thead, tbody, th, td, tr {
                    display: block;
                }

                    thead tr {
                        left: -9999px;
                        position: absolute;
                        top: -9999px;
                    }

                tr {
                    border: 1px solid #ccc;
                }

                td:nth-of-type(1):before {
                    content: "Employee No :";
                    font-weight: bold;
                }

                td:nth-of-type(2):before {
                    content: "Name :";
                    font-weight: bold;
                }

                td:nth-of-type(3):before {
                    content: "Department :";
                    font-weight: bold;
                }

                td:nth-of-type(4):before {
                    content: "Designation :";
                    font-weight: bold;
                }

                td:nth-of-type(5):before {
                    content: "Contact No :";
                    font-weight: bold;
                }
            }
        </style>
        <div class="row">
            <div class="col-xs-12">
                <div id="resize_wrapper">
                    <table id="grid" class="table dt-responsive table-striped table-bordered nowrap">
                        <thead>
                            <tr>
                                <th>Asset Type</th>
                                <th>Make</th>
                                <th>Serial Number</th>
                                <th>Quantity</th>
                                <th>Given On</th>
                                <th>Returned On</th>
                                <th>Returned</th>
                                <th>Remarks</th>
                            </tr>
                        </thead>
                        <tbody>
                            @for (var i = 0; i < Model.Count; i++)
                            {
                                var handover = Convert.ToDateTime(Model[i].HandoverOn).ToString("dd-MMM-yyyy");
                                var Modified = Convert.ToDateTime(Model[i].ModifiedOn).ToString("dd-MMM-yyyy hh:mm tt");


                                <tr id="@Model[i].CompanyAssetId">
                                    <td title="@Model[i].AssetsName.Name">
                                        @Html.DisplayFor(modelItem => Model[i].AssetsName.Name, new { id = "AssetsName" })
                                        @Html.HiddenFor(modelItem => Model[i].AssetStatus, new { id = "Assetstatus" })
                                    </td>
                                    <td title="@Model[i].Make">
                                        @Html.DisplayFor(modelItem => Model[i].Make)
                                    </td>
                                    <td title="@Model[i].SerialNumber">
                                        @Html.DisplayFor(modelItem => Model[i].SerialNumber)
                                    </td>
                                    <td title="@Model[i].Qty" class="text-center">
                                        @Html.DisplayFor(modelItem => Model[i].Qty)
                                    </td>
                                    <td title="@handover" class="text-center">
                                        @if (Model[i].HandoverOn != DateTime.MinValue)
                                        {
                                            @handover
                                            @Html.HiddenFor(modelItem => handover, new { id = "Handoveron" })
                                        }
                                    </td>

                                    @if (Model[i].ReturnedDate != DateTime.MinValue && Model[i].ReturnedDate != null)
                                    {
                                        var returnedon = Convert.ToDateTime(Model[i].ReturnedDate).ToString("dd-MMM-yyyy");
                                        <td title="@returnedon" class="text-center" id="tdReturnedDate + @Model[i].CompanyAssetId">
                                            @Html.Label(Convert.ToDateTime(Model[i].ReturnedDate).ToString("dd-MMM-yyyy"), new { style = "font-weight: normal !important;", id = "hdnReturnedDate" + Model[i].CompanyAssetId })
                                        </td>
                                    }
                                    else
                                    {
                                        <td class="text-center" id="tdReturnedDate + @Model[i].CompanyAssetId">
                                            @Html.Label("  ", new { id = "hdnReturnedDate" + Model[i].CompanyAssetId, style = "font-weight: normal !important;" })
                                        </td>
                                    }

                                    <td class="text-center handicon">
                                        <button type="button" title="Return" id="rejectBtn" data-toggle="modal" data-target="#approverModal" onclick="getreturndetails('@Model[i].CompanyAssetId', '@handover', '@Model[i].OffboardProcessID')" class="btn btn-sm btn-primary">
                                            <i class="fa fa-check-circle-o"></i> Return
                                        </button>
                                    </td>
                                    <td class="text-center handicon">
                                        <button type="button" title="Remarks" id="rejectBtn" data-toggle="modal" data-target="#modelRemarks" onclick="PopupRemarks('@Model[i].CompanyAssetId')" class="btn btn-sm btn-success">
                                            <i class="glyphicon glyphicon-list"></i>
                                        </button>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <footer class="main-footer navbar-fixed-bottom">
            <div class="row">
                <div class="col-md-6 hidemodified">
                    @if (Model[0].AssetStatus == "Cleared")
                    {
                        <span style="padding: 10px;"> Mod. By&nbsp;&nbsp;<b>@Model[0].ModifiedByName</b>&nbsp;&nbsp;on&nbsp;&nbsp;<b>@Html.DisplayFor(model => model[0].ModifiedOn)</b></span>
                    }
                </div>
                <div class="col-md-6 col-xs-12 text-right">
                    <button type="button" title="Cancel" class="btn btn-success btn-md pull-right" onclick="cancelapprove()"><i class="fa fa-refresh"></i> Cancel</button>
                </div>
            </div>
        </footer>
    </div>
</div>

<div class="modal fade" id="approverModal" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" title="Close" class="close" data-dismiss="modal" aria-hidden="false">×</button>
                <h4 class="modal-title">Returned Details</h4>
            </div>
            <div class="modal-body form-horizontal">
                <div id="GetReturnedform"></div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="modelRemarks" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" title="Close" class="close" data-dismiss="modal" aria-hidden="false">×</button>
                <h4 class="modal-title">Remarks</h4>
            </div>
            <div class="modal-body form-horizontal">
                <div id="divRemarks"></div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $("#Requestername").html(_EMPNAME);
    $("#Requestercode").html(_EMPCODE);
    $("#approverModal").draggable();
    $("#modelRemarks").draggable();
    $('#grid').DataTable({
        "paging": true,
        "lengthChange": false,
        "searching": false,
        "ordering": true,
        "info": true,
        "autoWidth": false,
        "aaSorting": [],
        pageResize: false
    });
    $(document).on('click',
        '.clickable',
        function (e) {
            var $this = $(this);
            if (!$this.hasClass('panel-collapsed')) {
                $this.parents('.box').find('.box-body').slideUp();
                $this.addClass('panel-collapsed');
                $this.find('i').removeClass('glyphicon-triangle-bottom').addClass('glyphicon-triangle-right');
            } else {
                $this.parents('.box').find('.box-body').slideDown();
                $this.removeClass('panel-collapsed');
                $this.find('i').removeClass('glyphicon-triangle-right').addClass('glyphicon-triangle-bottom');
            }
        });
    var _HANDOVERON;
    var _offboardProcessID;

    function getreturndetails(id, handoveron, offboardProcessID) {
        _HANDOVERON = handoveron;
        _offboardProcessID = offboardProcessID;
        $("#GetReturnedform").empty();
        $("#GetReturnedform").addClass('loaders');
        $.ajax({ 
            url: '@(Url.Action("ReturnedDetails", "EmployeeOffBoardProcess"))',
            type: 'GET',
            cache: false,
            data: { id: id },
            success: function (data) {
                setTimeout(function () {
                    $("#GetReturnedform").empty().html(data);
                    $("#GetReturnedform").removeClass('loaders');
                },
                    500);
            },
            error: function (data) {
            }
        });
    }

    function PopupRemarks(assetId) {
        $("#divRemarks").empty();
        $("#divRemarks").addClass('loaders');
        $.ajax({ 
            url: '@(Url.Action("RemarksDetails", "EmployeeOffBoardProcess"))',
            type: 'GET',
            cache: false,
            data: { id: assetId },
            success: function (data) {
                $("#divRemarks").empty().html(data);
                $("#divRemarks").removeClass('loaders');
            },
            error: function (data) {
            }
        });
    }

    function cancelapprove() { 
        location.href = '@(Url.Action("SearchAssetsClearance", "EmployeeOffBoardProcess"))?menuCode=ASSETCLR';
    }
</script>

cvt.officebau.com/Views/EmployeeOffBoardProcess/ExitInterviewDetails.cshtml
@model EmployeeOffBoardBo

@using (Html.BeginForm("ExitInterviewDetails", "EmployeeOffBoardProcess", FormMethod.Post, new { @class = "form-horizontal", id = "ExitReasonInterviewID" }))
{
    @Html.HiddenFor(model => model.Id, new { id = "ID" })
    @Html.HiddenFor(model => model.EmployeeId, new { id = "EmpID" })
    <input type="hidden" id="hdnDOJ" value="@Model.Doj.ToString("dd-MMM-yyyy")" />
    <div style="background-color: darkturquoise; padding: 5px;">
        <center>
            <strong> Exit Interview</strong>
        </center>
    </div>
    <div class="box-body" style="margin-top: 15px;">
        <div class="form-group">
            <label class="col-md-4 control-label">Relieved On<b class="Mandatory"> *</b></label>
            <div class="col-md-3">
                @Html.TextBoxFor(model => model.ActualRelievedDate, "{0:dd-MMM-yyyy}", new { @class = "form-control", id = "ActualRelievedDate" })
                @Html.ValidationMessageFor(model => model.ActualRelievedDate, "", new { @class = "text-danger" })
                <span id="spnRelievedDate" style="display: none;" class="text-danger field-validation-error" data-valmsg-replace="true">Relieved On must be greater than Date of Joining.</span>
            </div>
        </div>
        <div class="form-group">
            <label class="col-md-4 control-label">Exit Reason<b class="Mandatory"> *</b></label>
            <div class="col-md-3">
                @Html.DropDownListFor(model => Model.RelivingReasonId, new SelectList(Model.RelivingReasonList, "Value", "Text"), new { @class = "form-control", id = "RelivingReason" })
                @Html.ValidationMessageFor(model => model.RelivingReasonId, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <label class="col-md-4 control-label">Exit Feedback<b class="Mandatory"> *</b></label>
            <div class="col-md-3">
                @Html.TextAreaFor(model => model.RelievingComments, new { @class = "form-control",maxlength ="100" })
                @Html.ValidationMessageFor(model => model.RelievingComments, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
}

<script>
    $('#ActualRelievedDate').datepicker({
        autoclose: true,
        format: 'dd-M-yyyy',
        todayHighlight: true,
        startDate: '-0m'
    });

    if (@Model.Id == 0) {
        $("#ActualRelievedDate").val('');
    }
    $(document).ready(function() {
        $("#ActualRelievedDate").removeAttr("data-val-date");
    });
</script>
@Scripts.Render("~/bundles/jqueryval")

cvt.officebau.com/Views/EmployeeOffBoardProcess/OffBoardWithdrawHistory.cshtml
@model IEnumerable<EmployeeOffBoardBo>

<style>
    @@media only screen and (max-width: 760px), (min-device-width: 768px) and (max-device-width: 1024px) {
        table, thead, tbody, th, td, tr { display: block; }

        thead tr {
            left: -9999px;
            position: absolute;
            top: -9999px;
        }

        tr { border: 1px solid #ccc; }

        td:nth-of-type(1):before {
            content: "Employee Code :";
            font-weight: bold;
        }

        td:nth-of-type(2):before {
            content: "Employee Name :";
            font-weight: bold;
        }

        td:nth-of-type(5):before {
            content: "Withdraw Date :";
            font-weight: bold;
        }
    }
</style>

<div class="row">
    <div class="box-body">
        <div id="resize_wrapper">
            <table class="table table-bordered table-striped" id="withdrawTable">
                <thead>
                <tr>
                    <th width="15%">Request Date</th>
                    <th width="20%">Withdraw Date</th>
                    <th width="20%">Exp. Relieving Date</th>
                    <th width="30%">Reason / Rejected Remarks</th>
                    <th width="15%">Status</th>
                </tr>
                </thead>
                <tbody>
                @foreach (var item in Model)
                {
                    var Initiatedate = Convert.ToDateTime(item.InitiatedDate).ToString("dd-MMM-yyyy");
                    var WithdrawDate = Convert.ToDateTime(item.WithdrawDate).ToString("dd-MMM-yyyy");
                    var Relievingdate = Convert.ToDateTime(item.RelievingDate).ToString("dd-MMM-yyyy");
                    <tr>
                        <td title="@Initiatedate" class="text-center">
                            @Initiatedate
                        </td>
                        <td title="@WithdrawDate" class="text-center">
                            @WithdrawDate
                        </td>
                        <td title="@Relievingdate" class="text-center">
                            @Relievingdate
                        </td>
                        <td title="@item.Reason">
                            @{
                                if (item.Reason.Length > 35)
                                {
                                    @item.Reason.Substring(0, 35)
                                }
                                else
                                {
                                    @item.Reason
                                }
                            }

                        </td>
                        <td title="@item.StatusCode">
                            @item.StatusCode
                        </td>
                    </tr>
                }
                </tbody>
            </table>
        </div>
    </div>
</div>

<script>
    $('#withdrawTable').DataTable({
        "paging": false,
        "lengthChange": false,
        "searching": false,
        "ordering": true,
        "info": false,
        "autoWidth": false,
        "aaSorting": [],
        pageResize: true
    });
</script>